# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14YUeqqYJoR4Vur3CP42fAMuBLzQ5fiNo
"""

import tensorflow.compat.v1 as tf

hello = tf.constant("Hello, Tensorflow!")
sess = tf. Session()
print(sess.run(hello))#출력한다